[layout2] Use GetClientSize instead of GetClientSizeTuple
This fixes error:

  AttributeError: 'ModelWindow' object has no attribute
  'GetClientSizeTuple'. Did you mean: 'GetClientSize'?