[layout2] Call Add on BoxSizer instead of deprecated AddF
This fixes the following errors:

  AttributeError: 'BoxSizer' object has no attribute 'AddF'. Did you mean: 'Add'?